-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.campaign
(
    cf_id smallint NOT NULL,
    contact_id smallint NOT NULL,
    company_name text COLLATE pg_catalog."default" NOT NULL,
    description character varying(53) COLLATE pg_catalog."default" NOT NULL,
    goal numeric NOT NULL,
    pledged numeric NOT NULL,
    outcome character varying(10) COLLATE pg_catalog."default" NOT NULL,
    backers_count smallint NOT NULL,
    country character varying(2) COLLATE pg_catalog."default" NOT NULL,
    currency character varying(3) COLLATE pg_catalog."default" NOT NULL,
    launch_date date NOT NULL,
    end_date date NOT NULL,
    category_id character varying(5) COLLATE pg_catalog."default" NOT NULL,
    subcategory_id character varying(7) COLLATE pg_catalog."default" NOT NULL
);

CREATE TABLE IF NOT EXISTS public.category
(
    category_id character varying(5) COLLATE pg_catalog."default" NOT NULL,
    category character varying(12) COLLATE pg_catalog."default",
    CONSTRAINT category_pkey PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS public.contacts
(
    contact_id integer NOT NULL,
    first_name character varying(12) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(13) COLLATE pg_catalog."default" NOT NULL,
    email character varying(42) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT contacts_pkey PRIMARY KEY (contact_id)
);

CREATE TABLE IF NOT EXISTS public.subcategory
(
    subcategory_id character varying(7) COLLATE pg_catalog."default" NOT NULL,
    subcategory character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT subcategory_pkey PRIMARY KEY (subcategory_id)
);

ALTER TABLE IF EXISTS public.campaign
    ADD FOREIGN KEY (contact_id)
    REFERENCES public.contacts (contact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.campaign
    ADD FOREIGN KEY (category_id)
    REFERENCES public.category (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.campaign
    ADD FOREIGN KEY (subcategory_id)
    REFERENCES public.subcategory (subcategory_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;